# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-12-31T15:10:54+00:00

from __future__ import annotations

from datetime import date

from pydantic import BaseModel, EmailStr, constr


class PersonCreate(BaseModel):
    first_name: constr(min_length=1)
    last_name: constr(min_length=1)
    email: EmailStr
    phone: str | None = None
    date_of_birth: date | None = None


class Party(BaseModel):
    id: str | None = None
    display_name: str | None = None
    status: str | None = None
    party_type: str | None = None


class PersonResponse(BaseModel):
    id: str
    first_name: str
    last_name: str
    email: EmailStr
    phone: str | None = None
    party: Party
