# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-01-01T00:02:42+00:00

from __future__ import annotations

from pydantic import BaseModel, EmailStr


class Person(BaseModel):
    id: str | None = None
    name: str | None = None
    email: EmailStr | None = None


class PersonCreate(BaseModel):
    name: str | None = None
    email: EmailStr | None = None
